#!/usr/bin/env bash

things=(deployment replicaset statefulset daemonset service job hpa pod role rolebinding serviceaccount)

if [[ -z $1 ]]; then
  echo "Usage: kubenukem [namespace] name [--unsafe]"
  echo
  echo "Nukes (deletes) all resources with a particular *name* in a particular namespace from a Kubernetes cluster"
  echo
  echo "  namespace       if not provided, 'default' namespace is used"
  echo "  name            name of resources to delete, can be partial name (like grep)"
  echo "  --unsafe        deletes also 'clusterrole' and 'clusterrolebinding' which are global (not namespace specific!)"
  exit 1
fi

namespace=$1
service=$2

if [[ -z $service ]]; then
  service=$1
  namespace=default
fi

if [[ $3 == "--unsafe" ]]; then
  things+=(clusterrole clusterrolebinding)
fi

for thing in "${things[@]}"; do
	for thingy in "$(kubectl -n "$namespace" get "$thing" | grep "$service")"; do
		for t in $(echo "$thingy"| cut -d' ' -f1); do
			kubectl -n "$namespace" delete "$thing" "$t" --now --force --cascade=false
		done
	done
done
